
// This file has been generated by the GUI designer. Do not modify.
namespace DiveIn.Properties
{
	public partial class RegisterDivers
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Entry diverNameEntry;

		private global::Gtk.Entry clubEntry;

		private global::Gtk.Entry jump1Entry;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Entry jump2Entry;

		private global::Gtk.Entry jump3Entry;

		private global::Gtk.Button registerDiver;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Button startCompButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DiveIn.Properties.RegisterDivers
			this.Name = "DiveIn.Properties.RegisterDivers";
			this.Title = global::Mono.Unix.Catalog.GetString("RegisterDivers");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DiveIn.Properties.RegisterDivers.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.diverNameEntry = new global::Gtk.Entry();
			this.diverNameEntry.CanFocus = true;
			this.diverNameEntry.Name = "diverNameEntry";
			this.diverNameEntry.Text = global::Mono.Unix.Catalog.GetString("Diver name...");
			this.diverNameEntry.IsEditable = true;
			this.diverNameEntry.InvisibleChar = '●';
			this.vbox5.Add(this.diverNameEntry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.diverNameEntry]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.clubEntry = new global::Gtk.Entry();
			this.clubEntry.CanFocus = true;
			this.clubEntry.Name = "clubEntry";
			this.clubEntry.Text = global::Mono.Unix.Catalog.GetString("Divers club...");
			this.clubEntry.IsEditable = true;
			this.clubEntry.InvisibleChar = '●';
			this.vbox5.Add(this.clubEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.clubEntry]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.jump1Entry = new global::Gtk.Entry();
			this.jump1Entry.CanFocus = true;
			this.jump1Entry.Name = "jump1Entry";
			this.jump1Entry.Text = global::Mono.Unix.Catalog.GetString("Jump one...");
			this.jump1Entry.IsEditable = true;
			this.jump1Entry.InvisibleChar = '●';
			this.vbox5.Add(this.jump1Entry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.jump1Entry]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add(this.vbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.jump2Entry = new global::Gtk.Entry();
			this.jump2Entry.CanFocus = true;
			this.jump2Entry.Name = "jump2Entry";
			this.jump2Entry.Text = global::Mono.Unix.Catalog.GetString("Jump two...");
			this.jump2Entry.IsEditable = true;
			this.jump2Entry.InvisibleChar = '●';
			this.vbox6.Add(this.jump2Entry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.jump2Entry]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.jump3Entry = new global::Gtk.Entry();
			this.jump3Entry.CanFocus = true;
			this.jump3Entry.Name = "jump3Entry";
			this.jump3Entry.Text = global::Mono.Unix.Catalog.GetString("Jump three...");
			this.jump3Entry.IsEditable = true;
			this.jump3Entry.InvisibleChar = '●';
			this.vbox6.Add(this.jump3Entry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.jump3Entry]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add(this.vbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox6]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.registerDiver = new global::Gtk.Button();
			this.registerDiver.CanFocus = true;
			this.registerDiver.Name = "registerDiver";
			this.registerDiver.UseUnderline = true;
			this.registerDiver.Label = global::Mono.Unix.Catalog.GetString("Register diver");
			this.vbox4.Add(this.registerDiver);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.registerDiver]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox4.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator1]));
			w9.Position = 3;
			w9.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.startCompButton = new global::Gtk.Button();
			this.startCompButton.CanFocus = true;
			this.startCompButton.Name = "startCompButton";
			this.startCompButton.UseUnderline = true;
			this.startCompButton.Label = global::Mono.Unix.Catalog.GetString("Start competition");
			this.vbox4.Add(this.startCompButton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.startCompButton]));
			w10.PackType = ((global::Gtk.PackType)(1));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 460;
			this.DefaultHeight = 277;
			this.Show();
			this.registerDiver.Clicked += new global::System.EventHandler(this.OnRegisterDiverClicked);
			this.startCompButton.Clicked += new global::System.EventHandler(this.OnStartCompButtonClicked);
		}
	}
}
