
// This file has been generated by the GUI designer. Do not modify.
namespace DiveIn.Properties
{
	public partial class JudgeScoring
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Frame frame4;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.Table table4;

		private global::Gtk.Button score1;

		private global::Gtk.Button score10;

		private global::Gtk.Button score1five;

		private global::Gtk.Button score2;

		private global::Gtk.Button score25;

		private global::Gtk.Button score3;

		private global::Gtk.Button score35;

		private global::Gtk.Button score4;

		private global::Gtk.Button score45;

		private global::Gtk.Button score5;

		private global::Gtk.Button score55;

		private global::Gtk.Button score6;

		private global::Gtk.Button score65;

		private global::Gtk.Button score7;

		private global::Gtk.Button score75;

		private global::Gtk.Button score8;

		private global::Gtk.Button score85;

		private global::Gtk.Button score9;

		private global::Gtk.Button score95;

		private global::Gtk.Button scoreZero;

		private global::Gtk.Button scoreZeroFive;

		private global::Gtk.Label GtkLabel20;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textviewJudge;

		private global::Gtk.Label GtkLabel21;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textviewCurrentDiver;

		private global::Gtk.Label GtkLabel22;

		private global::Gtk.Button saveScore;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DiveIn.Properties.JudgeScoring
			this.WidthRequest = 40;
			this.HeightRequest = 40;
			this.Name = "DiveIn.Properties.JudgeScoring";
			this.Title = global::Mono.Unix.Catalog.GetString("JudgeScoring");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DiveIn.Properties.JudgeScoring.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame4 = new global::Gtk.Frame();
			this.frame4.Name = "frame4";
			this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame4.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table(((uint)(7)), ((uint)(3)), true);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.score1 = new global::Gtk.Button();
			this.score1.CanFocus = true;
			this.score1.Name = "score1";
			this.score1.UseUnderline = true;
			this.score1.Label = global::Mono.Unix.Catalog.GetString("1");
			this.table4.Add(this.score1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table4[this.score1]));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score10 = new global::Gtk.Button();
			this.score10.CanFocus = true;
			this.score10.Name = "score10";
			this.score10.UseUnderline = true;
			this.score10.Label = global::Mono.Unix.Catalog.GetString("10");
			this.table4.Add(this.score10);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4[this.score10]));
			w2.TopAttach = ((uint)(6));
			w2.BottomAttach = ((uint)(7));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score1five = new global::Gtk.Button();
			this.score1five.CanFocus = true;
			this.score1five.Name = "score1five";
			this.score1five.UseUnderline = true;
			this.score1five.Label = global::Mono.Unix.Catalog.GetString("1.5");
			this.table4.Add(this.score1five);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4[this.score1five]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score2 = new global::Gtk.Button();
			this.score2.CanFocus = true;
			this.score2.Name = "score2";
			this.score2.UseUnderline = true;
			this.score2.Label = global::Mono.Unix.Catalog.GetString("2");
			this.table4.Add(this.score2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4[this.score2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score25 = new global::Gtk.Button();
			this.score25.CanFocus = true;
			this.score25.Name = "score25";
			this.score25.UseUnderline = true;
			this.score25.Label = global::Mono.Unix.Catalog.GetString("2.5");
			this.table4.Add(this.score25);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4[this.score25]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score3 = new global::Gtk.Button();
			this.score3.CanFocus = true;
			this.score3.Name = "score3";
			this.score3.UseUnderline = true;
			this.score3.Label = global::Mono.Unix.Catalog.GetString("3");
			this.table4.Add(this.score3);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4[this.score3]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score35 = new global::Gtk.Button();
			this.score35.CanFocus = true;
			this.score35.Name = "score35";
			this.score35.UseUnderline = true;
			this.score35.Label = global::Mono.Unix.Catalog.GetString("3.5");
			this.table4.Add(this.score35);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4[this.score35]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score4 = new global::Gtk.Button();
			this.score4.CanFocus = true;
			this.score4.Name = "score4";
			this.score4.UseUnderline = true;
			this.score4.Label = global::Mono.Unix.Catalog.GetString("4");
			this.table4.Add(this.score4);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table4[this.score4]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(2));
			w8.RightAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score45 = new global::Gtk.Button();
			this.score45.CanFocus = true;
			this.score45.Name = "score45";
			this.score45.UseUnderline = true;
			this.score45.Label = global::Mono.Unix.Catalog.GetString("4.5");
			this.table4.Add(this.score45);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table4[this.score45]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score5 = new global::Gtk.Button();
			this.score5.CanFocus = true;
			this.score5.Name = "score5";
			this.score5.UseUnderline = true;
			this.score5.Label = global::Mono.Unix.Catalog.GetString("5");
			this.table4.Add(this.score5);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4[this.score5]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score55 = new global::Gtk.Button();
			this.score55.CanFocus = true;
			this.score55.Name = "score55";
			this.score55.UseUnderline = true;
			this.score55.Label = global::Mono.Unix.Catalog.GetString("5.5");
			this.table4.Add(this.score55);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table4[this.score55]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score6 = new global::Gtk.Button();
			this.score6.CanFocus = true;
			this.score6.Name = "score6";
			this.score6.UseUnderline = true;
			this.score6.Label = global::Mono.Unix.Catalog.GetString("6");
			this.table4.Add(this.score6);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table4[this.score6]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score65 = new global::Gtk.Button();
			this.score65.CanFocus = true;
			this.score65.Name = "score65";
			this.score65.UseUnderline = true;
			this.score65.Label = global::Mono.Unix.Catalog.GetString("6.5");
			this.table4.Add(this.score65);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4[this.score65]));
			w13.TopAttach = ((uint)(4));
			w13.BottomAttach = ((uint)(5));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score7 = new global::Gtk.Button();
			this.score7.CanFocus = true;
			this.score7.Name = "score7";
			this.score7.UseUnderline = true;
			this.score7.Label = global::Mono.Unix.Catalog.GetString("7");
			this.table4.Add(this.score7);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4[this.score7]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score75 = new global::Gtk.Button();
			this.score75.CanFocus = true;
			this.score75.Name = "score75";
			this.score75.UseUnderline = true;
			this.score75.Label = global::Mono.Unix.Catalog.GetString("7.5");
			this.table4.Add(this.score75);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4[this.score75]));
			w15.TopAttach = ((uint)(5));
			w15.BottomAttach = ((uint)(6));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score8 = new global::Gtk.Button();
			this.score8.CanFocus = true;
			this.score8.Name = "score8";
			this.score8.UseUnderline = true;
			this.score8.Label = global::Mono.Unix.Catalog.GetString("8");
			this.table4.Add(this.score8);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table4[this.score8]));
			w16.TopAttach = ((uint)(5));
			w16.BottomAttach = ((uint)(6));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score85 = new global::Gtk.Button();
			this.score85.CanFocus = true;
			this.score85.Name = "score85";
			this.score85.UseUnderline = true;
			this.score85.Label = global::Mono.Unix.Catalog.GetString("8.5");
			this.table4.Add(this.score85);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4[this.score85]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(2));
			w17.RightAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score9 = new global::Gtk.Button();
			this.score9.CanFocus = true;
			this.score9.Name = "score9";
			this.score9.UseUnderline = true;
			this.score9.Label = global::Mono.Unix.Catalog.GetString("9");
			this.table4.Add(this.score9);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table4[this.score9]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.score95 = new global::Gtk.Button();
			this.score95.CanFocus = true;
			this.score95.Name = "score95";
			this.score95.UseUnderline = true;
			this.score95.Label = global::Mono.Unix.Catalog.GetString("9.5");
			this.table4.Add(this.score95);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table4[this.score95]));
			w19.TopAttach = ((uint)(6));
			w19.BottomAttach = ((uint)(7));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.scoreZero = new global::Gtk.Button();
			this.scoreZero.WidthRequest = 50;
			this.scoreZero.HeightRequest = 50;
			this.scoreZero.CanFocus = true;
			this.scoreZero.Name = "scoreZero";
			this.scoreZero.UseUnderline = true;
			this.scoreZero.Label = global::Mono.Unix.Catalog.GetString("0");
			this.table4.Add(this.scoreZero);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table4[this.scoreZero]));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.scoreZeroFive = new global::Gtk.Button();
			this.scoreZeroFive.CanFocus = true;
			this.scoreZeroFive.Name = "scoreZeroFive";
			this.scoreZeroFive.UseUnderline = true;
			this.scoreZeroFive.Label = global::Mono.Unix.Catalog.GetString("0.5");
			this.table4.Add(this.scoreZeroFive);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table4[this.scoreZeroFive]));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add(this.table4);
			this.frame4.Add(this.GtkAlignment2);
			this.GtkLabel20 = new global::Gtk.Label();
			this.GtkLabel20.Name = "GtkLabel20";
			this.GtkLabel20.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Score</b>");
			this.GtkLabel20.UseMarkup = true;
			this.frame4.LabelWidget = this.GtkLabel20;
			this.vbox3.Add(this.frame4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame4]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textviewJudge = new global::Gtk.TextView();
			this.textviewJudge.CanFocus = true;
			this.textviewJudge.Name = "textviewJudge";
			this.GtkScrolledWindow1.Add(this.textviewJudge);
			this.GtkAlignment.Add(this.GtkScrolledWindow1);
			this.frame3.Add(this.GtkAlignment);
			this.GtkLabel21 = new global::Gtk.Label();
			this.GtkLabel21.WidthRequest = 300;
			this.GtkLabel21.Name = "GtkLabel21";
			this.GtkLabel21.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Judge scoring</b>");
			this.GtkLabel21.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel21;
			this.vbox3.Add(this.frame3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame3]));
			w28.Position = 1;
			this.vbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
			w29.Position = 0;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewCurrentDiver = new global::Gtk.TextView();
			this.textviewCurrentDiver.CanFocus = true;
			this.textviewCurrentDiver.Name = "textviewCurrentDiver";
			this.GtkScrolledWindow.Add(this.textviewCurrentDiver);
			this.GtkAlignment1.Add(this.GtkScrolledWindow);
			this.frame2.Add(this.GtkAlignment1);
			this.GtkLabel22 = new global::Gtk.Label();
			this.GtkLabel22.WidthRequest = 300;
			this.GtkLabel22.Name = "GtkLabel22";
			this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Current diver</b>");
			this.GtkLabel22.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel22;
			this.vbox2.Add(this.frame2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
			w34.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.saveScore = new global::Gtk.Button();
			this.saveScore.CanFocus = true;
			this.saveScore.Name = "saveScore";
			this.saveScore.UseUnderline = true;
			this.saveScore.Label = global::Mono.Unix.Catalog.GetString("Save score");
			this.vbox2.Add(this.saveScore);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.saveScore]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 651;
			this.DefaultHeight = 621;
			this.Show();
			this.scoreZeroFive.Pressed += new global::System.EventHandler(this.OnScoreZeroFivePressed);
			this.scoreZero.Clicked += new global::System.EventHandler(this.OnScoreZeroClicked);
			this.score95.Clicked += new global::System.EventHandler(this.OnScore95Clicked);
			this.score9.Clicked += new global::System.EventHandler(this.OnScore9Clicked);
			this.score85.Clicked += new global::System.EventHandler(this.OnScore85Clicked);
			this.score8.Clicked += new global::System.EventHandler(this.OnScore8Clicked);
			this.score75.Clicked += new global::System.EventHandler(this.OnScore75Clicked);
			this.score7.Clicked += new global::System.EventHandler(this.OnScore7Clicked);
			this.score65.Clicked += new global::System.EventHandler(this.OnScore65Clicked);
			this.score6.Clicked += new global::System.EventHandler(this.OnScore6Clicked);
			this.score55.Clicked += new global::System.EventHandler(this.OnScore55Clicked);
			this.score5.Clicked += new global::System.EventHandler(this.OnScore5Clicked);
			this.score45.Clicked += new global::System.EventHandler(this.OnScore45Clicked);
			this.score4.Clicked += new global::System.EventHandler(this.OnScore4Clicked);
			this.score35.Clicked += new global::System.EventHandler(this.OnScore35Clicked);
			this.score3.Clicked += new global::System.EventHandler(this.OnScore3Clicked);
			this.score25.Clicked += new global::System.EventHandler(this.OnScore25Clicked);
			this.score2.Clicked += new global::System.EventHandler(this.OnScore2Clicked);
			this.score1five.Clicked += new global::System.EventHandler(this.OnScore1fiveClicked);
			this.score10.Clicked += new global::System.EventHandler(this.OnScore10Clicked);
			this.score1.Clicked += new global::System.EventHandler(this.OnScore1Clicked);
			this.saveScore.Clicked += new global::System.EventHandler(this.OnSaveScoreClicked);
		}
	}
}
